# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name : IMAMAGENT
  version: 3.232.1

stages:
  - stage: 'Junit'
    displayName: 'Junit stage'
    jobs:
      - job: 'JUnitTest'
        displayName: 'Running Unit Tests'
        steps:
          - script: echo 'Running Spring Demo app Unit Test'
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'Test'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              codeCoverageToolOption: 'JaCoCo'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
              checkStyleRunAnalysis: true
              pmdRunAnalysis: true